#! /bin/bash

# Set up symlinks
ln -nfs "$(pwd)/ruby/.gemrc"            "$HOME/.gemrc"
ln -nfs "$(pwd)/ruby/.irbrc"            "$HOME/.irbrc"
ln -nfs "$(pwd)/bin"                    "$HOME/.bin"

ln -nfs "$(pwd)/zsh/.zshrc"             "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zsh"               "$HOME/.zsh"
ln -nfs "$(pwd)/.ruby-version"          "$HOME/.ruby-version"

SUBLIME_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
ln -nfs "$(pwd)/sublime/Preferences.sublime-settings" "$SUBLIME_DIR/Preferences.sublime-settings"
ln -nfs "$(pwd)/sublime/Default (OSX).sublime-keymap" "$SUBLIME_DIR/Default (OSX).sublime-keymap"

if ! [ -d "$HOME/.atom" ]
then
  mkdir "$HOME/.atom"
fi

ln -nfs "$(pwd)/atom/config.cson" "$HOME/.atom/config.cson"
ln -nfs "$(pwd)/atom/styles.less" "$HOME/.atom/styles.less"

ln -nfs "$(pwd)/git/.gitignore_global"  "$HOME/.gitignore_global"

git config --global color.diff always
git config --global user.email "martijn@keplar.nl"
git config --global user.name "Martijn Bleeker"
git config --global core.excludesfile "$HOME/.gitignore_global"
git config --global merge.ff only
