#! /bin/bash

# Set up symlinks
ln -nfs "$(pwd)/ruby/.gemrc"            "$HOME/.gemrc"
ln -nfs "$(pwd)/ruby/.irbrc"            "$HOME/.irbrc"
ln -nfs "$(pwd)/ruby/.rspec"            "$HOME/.rspec"
ln -nfs "$(pwd)/bin"                    "$HOME/.bin"

ln -nfs "$(pwd)/zsh/.zshrc"             "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zsh"               "$HOME/.zsh"
ln -nfs "$(pwd)/.ruby-version"          "$HOME/.ruby-version"
ln -nfs "$(pwd)/asdf/.asdfrc"           "$HOME/.asdfrc"
ln -nfs "$(pwd)/.tool-versions"         "$HOME/.tool-versions"

SUBLIME_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
ln -nfs "$(pwd)/sublime/Preferences.sublime-settings" "$SUBLIME_DIR/Preferences.sublime-settings"
ln -nfs "$(pwd)/sublime/Default (OSX).sublime-keymap" "$SUBLIME_DIR/Default (OSX).sublime-keymap"

if ! [ -d "$HOME/.atom" ]
then
  mkdir "$HOME/.atom"
fi

ln -nfs "$(pwd)/vim/.vimrc"             "$HOME/.vimrc"
ln -nfs "$(pwd)/vim/.gvimrc"            "$HOME/.gvimrc"
ln -nfs "$(pwd)/vim/.vim"               "$HOME/.vim"
ln -nfs "$(pwd)/vim/.vim"               "$HOME/.config/nvim"

ln -nfs "$(pwd)/atom/config.cson"       "$HOME/.atom/config.cson"
ln -nfs "$(pwd)/atom/styles.less"       "$HOME/.atom/styles.less"

ln -nfs "$(pwd)/hammerspoon" "$HOME/.hammerspoon"
ln -nfs "$(pwd)/git/.gitignore_global" "$HOME/.gitignore_global"
ln -nfs "$(pwd)/.agignore" "$HOME/.agignore"

ln -nfs "$(pwd)/mysql/.my.cnf" "$HOME/.my.cnf"

mkdir -p "$HOME/.gnupg"
ln -nfs "$(pwd)/.gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"
ln -nfs "$(pwd)/.gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"

# Copy powerlines
for file in ./powerline-fonts/Meslo/*.otf; do
  cp -f "$file" "$HOME/Library/Fonts/"
done

# https://github.com/postmodern/chruby/issues/196#issuecomment-23826171
[[ -e /etc/zshenv ]] && sudo mv /etc/zshenv /etc/zprofile

# Global Git configuration
git config --global color.diff always
git config --global user.email "martijn@thebleacher.com"
git config --global user.name "Martijn Bleeker"
git config --global user.signingkey 766C9272
git config --global core.excludesfile "$HOME/.gitignore_global"
git config --global merge.ff only
git config --global rebase.autosquash true
git config --global push.default current
git config --global remote.origin.prune true
git config --global transfer.fsckobjects true
git config --global commit.gpgsign true
git config --global tag.forceSignAnnotated true
git config --global pull.rebase false
git config --global init.defaultBranch main
